### ISSUE TITLE
Missing doc: how to use ActiveRecords as data source

### ISSUE THREAD

**Issue by butterflyx** [Sibilino/yii2-dygraphswidget#1]
Thank you for this widget.

It would be very helpfull, if the documentation would contain an example where the data source is an ActiveDataProvider e.g. to visualize table data in a typical CRUD index-view.

**Comment by Sibilino** [comment]
Hi,

Sounds useful. I'll try to update the widget over this weekend.

Cheers

2015-07-07 17:13 GMT+02:00 butterflyx notifications@github.com:

**Comment by butterflyx** [comment]
Great, thank you! =)
I'm quite new to Yii2 and sure, that there are better ways, than mine.

Actually I have a second query for the diagramm instead:

```
 $dblist = Count::find()
        ->where(['user_id' => \Yii::$app->user->identity->id])
        ->orderBy('created_at')
        ->all();

    $diaList = ArrayHelper::map($dblist,"created_at","count");

    foreach ($diaList as $day => $count) {
        $date = new \DateTime($day);
        $list[] = [$date, $count]; 
    }

    return $this->render('index', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'diaList' => $list,
    ]);
```

So I get this array in the view:

```
    Array ( [0] => Array ( [0] => DateTime Object ( [date] => 2015-06-28 08:25:03 [timezone_type] => 3 [timezone] => UTC ) [1] => 16 ) [1] => Array ( [0] => DateTime Object ( [date] => 2015-07-03 20:14:27 [timezone_type] => 3 [timezone] => UTC ) [1] => 1 ) [2] => Array ( [0] => DateTime Object ( [date] => 2015-07-03 20:14:40 [timezone_type] => 3 [timezone] => UTC ) [1] => 44 ) )
```

and using this code:

```
<?php        

    echo DygraphsWidget::widget([
        'data' => $diaList,
        'options' => [
            'labels' => ['Day','Arrows'],
            'title'=> 'My main Graph',
            //...
        ],
    ]);
?>
```

No error message, but the diagram doesn't render (empty):
![download](https://cloud.githubusercontent.com/assets/5388631/8571657/748192ba-2588-11e5-9480-0770b03ec36a.png)

So, I would be happy, if you could update with two elements:
1. avoid additional DB query and using e.g. given $dataProvider
2. using dygraphs with DateTime-Objects as data

**Comment by Sibilino** [comment]
Those do sound like necessary features, I'll try to add them soon.

In the meantime, can you try leaving `$date` as string (i. e., `$date = $day` in your code) and adding `'xIsDate' => true` in the widget's config array? That way the date strings will automatically be parsed by the widget.

**Comment by butterflyx** [comment]
Thanks for this hint.

So I get this array

```
Array ( [0] => Array ( [0] => 2015-06-28 08:25:03 [1] => 16 ) [1] => Array ( [0] => 2015-07-03 20:14:27 [1] => 1 ) [2] => Array ( [0] => 2015-07-03 20:14:40 [1] => 44 ) )
```

result ist no error message but still an empty graph, same as before

**Comment by Sibilino** [comment]
I have tested your data array manually and it appears to work for me.
Here's what I've used:

``` php
DygraphsWidget::widget([
    'xIsDate' => true,
    'data' => [
        ["2015-06-28 08:25:03", 16],
        ["2015-07-03 20:14:27", 1],
        ["2015-07-03 20:14:40", 44],
    ],
    'options' => [
        'labels' => ['Day','Arrows'],
        'title'=> 'My main Graph',
    ],
]);
```

**Comment by butterflyx** [comment]
Ahhhh, that was the point! It's working now. Thanks again!
I had put it 'xIsDate' in the subarray 'options', my mistake.
